name: VCP Fix Search Tags

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'  # Lunes 7am BA (10am UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Fix Search Tags
        env:
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
        run: python fix_search_tags.py
